### GET findAll
GET http://localhost:3000/items

### GET findById
GET http://localhost:3000/items/71901791-9855-4278-a9d7-31e3e8aab50b

### POST create(1)
POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "My Awesome Item1",
  "price": 10.00,
  "description": "1 on the market!"
}

### POST create(2)
POST http://localhost:3000/items
Content-Type: application/json

{
  "id": "2",
  "name": "My Awesome Item2",
  "price": 20.00,
  "description": "2 on the market!"
}

### PATCH updateStatus
PATCH http://localhost:3000/items/71901791-9855-4278-a9d7-31e3e8aab50b

### DELETE delete
DELETE http://localhost:3000/items/71901791-9855-4278-a9d7-31e3e8aab50b